parameters:
    netgen_ibexa_scheduled_visibility.enabled: false
    netgen_ibexa_scheduled_visibility.type: 'location'
    netgen_ibexa_scheduled_visibility.content_types.all: false
    netgen_ibexa_scheduled_visibility.content_types.allowed: []
    netgen_ibexa_scheduled_visibility.sections.hidden.section_id: 0
    netgen_ibexa_scheduled_visibility.sections.visible.section_id: 0
    netgen_ibexa_scheduled_visibility.object_states.object_state_group_id: 0
    netgen_ibexa_scheduled_visibility.object_states.hidden.object_state_id: 0
    netgen_ibexa_scheduled_visibility.object_states.visible.object_state_id: 0

services:
    Netgen\Bundle\IbexaScheduledVisibilityBundle\EventListener\ScheduledVisibilityListener:
        arguments:
            - '@Netgen\Bundle\IbexaScheduledVisibilityBundle\Service\ScheduledVisibilityService'
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: ngscheduledvisibility }

    _instanceof:
        Netgen\Bundle\IbexaScheduledVisibilityBundle\ScheduledVisibility\ScheduledVisibilityInterface:
            tags: [ 'netgen.ibexa_scheduled_visibility.handler' ]

    Netgen\Bundle\IbexaScheduledVisibilityBundle\Service\ScheduledVisibilityService:
        arguments:
            - !tagged_iterator { tag: 'netgen.ibexa_scheduled_visibility.handler' }
            - '%netgen_ibexa_scheduled_visibility.type%'
            - '%netgen_ibexa_scheduled_visibility.enabled%'
            - '%netgen_ibexa_scheduled_visibility.content_types.all%'
            - '%netgen_ibexa_scheduled_visibility.content_types.allowed%'

    Netgen\Bundle\IbexaScheduledVisibilityBundle\ScheduledVisibility\Handler\Location:
        arguments:
            - '@ibexa.api.repository'
            - '@ibexa.api.service.content'
            - '@ibexa.api.service.location'

    Netgen\Bundle\IbexaScheduledVisibilityBundle\ScheduledVisibility\Handler\Section:
        arguments:
            - '@ibexa.api.repository'
            - '@ibexa.api.service.section'
            - '%netgen_ibexa_scheduled_visibility.sections.hidden.section_id%'
            - '%netgen_ibexa_scheduled_visibility.sections.visible.section_id%'

    Netgen\Bundle\IbexaScheduledVisibilityBundle\ScheduledVisibility\Handler\ObjectState:
        arguments:
            - '@ibexa.api.repository'
            - '@ibexa.api.service.object_state'
            - '%netgen_ibexa_scheduled_visibility.object_states.object_state_group_id%'
            - '%netgen_ibexa_scheduled_visibility.object_states.hidden.object_state_id%'
            - '%netgen_ibexa_scheduled_visibility.object_states.visible.object_state_id%'

    Netgen\Bundle\IbexaScheduledVisibilityBundle\Command\ToggleContentVisibilityCommand:
        arguments:
            - '@ibexa.api.repository'
            - '@Netgen\Bundle\IbexaScheduledVisibilityBundle\Service\ScheduledVisibilityService'
            - '%netgen_ibexa_scheduled_visibility.enabled%'
            - '%netgen_ibexa_scheduled_visibility.content_types.all%'
            - '%netgen_ibexa_scheduled_visibility.content_types.allowed%'
        tags:
            - { name: console.command, command: 'ngscheduledvisibility:content:toggle-visibility' }
